# https://docs.github.com/en/actions/about-github-actions/understanding-github-actions#workflows
name: Azure Plan Workflow

# https://docs.github.com/en/actions/about-github-actions/understanding-github-actions#events
on:
  pull_request:
    branches:
      - main
      
# Special permissions required for OIDC authentication
# configure github actions - https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
# configure azure resources - https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect#prerequisites
# register an app in microsoft entra id tenant - https://learn.microsoft.com/en-us/entra/identity-platform/howto-create-service-principal-portal#prerequisites

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

# https://docs.github.com/en/actions/about-github-actions/understanding-github-actions#jobs
jobs:
  static-analysis:
    # Define the job to run on the latest Ubuntu runner https://docs.github.com/en/actions/about-github-actions/understanding-github-actions#runners
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4  # Use the latest version of the checkout action https://docs.github.com/en/actions/about-github-actions/understanding-github-actions#actions

    - name: TFSec PR Commenter
      uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        tfsec_args: --minimum-severity CRITICAL
        github_token: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        working_directory: '' # https://github.com/aquasecurity/tfsec-pr-commenter-action/issues/90

  terraform-plan:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Terraform install
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.8"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: terraform init -reconfigure
      working-directory: ./infra/parent_directory/

    - name: Terraform Plan
      run: terraform plan -out "tfplan"
      working-directory: ./infra/parent_directory/

    - name: Convert Terraform Plan to JSON
      run: terraform show -json tfplan | grep '^{.*}$' > tfplan.json
      working-directory: ./infra/parent_directory/

    # https://www.openpolicyagent.org/docs/latest/
    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: "2.2.0"

    - name: Run OPA Authz Policy Check
      id: opa-authz-check
      run: |
        result=$(opa eval --data .github/workflows/terraform.rego --input ./infra/parent_directory/tfplan.json "data.terraform.analysis.authz" --format=json | jq '.result[0].expressions[0].value')
        echo $result
      continue-on-error: false
    
    - name: Run OPA Score Policy Check
      id: opa-score-check
      run: opa eval --data .github/workflows/terraform.rego --input ./infra/parent_directory/tfplan.json "data.terraform.analysis.score"
      continue-on-error: false

    needs: static-analysis

      
